# Generated by Django 2.2.6 on 2019-10-18 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=254)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fbid', models.CharField(max_length=254)),
                ('photo', models.TextField(blank=True)),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, max_length=255)),
                ('pin', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('invoice_sending_email', models.EmailField(max_length=254, unique=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
