# Generated by Django 2.2.6 on 2019-10-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='amount_bbox',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='due_date_bbox',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='invoice_no_bbox',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
