# Generated by Django 2.2.6 on 2019-10-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191020_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active_access_token',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='active_subscription_id',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
