# Generated by Django 2.2.6 on 2019-10-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20191019_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoince_no',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
