# Generated by Django 2.2.6 on 2019-10-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20191019_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
