# Generated by Django 2.2.6 on 2019-10-20 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20191019_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.Bill'),
        ),
    ]
