# Generated by Django 2.2.6 on 2019-10-20 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20191020_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 20, 8, 24, 25, 321617, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
