# Generated by Django 2.2.6 on 2019-10-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_payment_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='accounts.Vendor'),
        ),
    ]
